spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:railway}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:wagner}
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false